### ISSUE TITLE
Is `ObjectAssert(AtomicReference)` rendundant?

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#1536]
I noticed there is an `ObjectAssert(AtomicReference<ACTUAL>) ` constructor which is used nowhere (including tests):

https://github.com/assertj/assertj-core/blob/30bfbbc257d1a5b59563323b5eea29099d73926f/src/main/java/org/assertj/core/api/ObjectAssert.java#L39-L41

At the same time there is an `AtomicReferenceAssert(AtomicReference<V>)` constructor which is actually used by `Assertions`:

https://github.com/assertj/assertj-core/blob/30bfbbc257d1a5b59563323b5eea29099d73926f/src/main/java/org/assertj/core/api/AtomicReferenceAssert.java#L28-L30

https://github.com/assertj/assertj-core/blob/30bfbbc257d1a5b59563323b5eea29099d73926f/src/main/java/org/assertj/core/api/Assertions.java#L1085-L1087

Clearly they are not the same as the `ObjectAssert` is getting the actual value before creating the assertion, but I was wondering why there is this shortcut for a particular use case, which must be used directly as it's not accessible via `Assertions`.

At first glance, it seems to me that the former could be deprecated or removed (breaking change), since `actual.get()` could be easily called inside` assertThat()` by the end user.

**Comment by joel-costigliola** [comment]
AFAIR the idea was to make it easy to get the assertions for the underlying atomic object but it was not possible to expose it in `Assertions.assertThat` due to the existing atomic assertions.

The https://github.com/joel-costigliola/assertj-core/commit/24f054a2c72988d543f545c801401f1290693962 commit shows the same approach for other atomic types.

I think this was not a great idea as few people would be aware of this, retrospectively it should not have been (moreover there is no tests for it).

The best thing is to deprecate IMO (and remove it in 2 or 3 versions).

**Comment by scordio** [comment]
Would it help to use a similar approach to:

https://github.com/joel-costigliola/assertj-core/blob/83cd126d183cf55fd3a16cc40c0f5f634ed71dc5/src/main/java/org/assertj/core/api/AbstractOptionalAssert.java#L433-L436

having a `get()` method which performs some preliminary assertions and then returns the underlying atomic object as the new one under test?
