### ISSUE TITLE
`isEqualTo()` argument type is not checked in compile-time

### ISSUE THREAD

**Issue by RamazanYapparov** [assertj/assertj#1910]
#### Summary
When making assertions on some type with `isEqualTo` assert, its parameter type is not checked at compile time, because it has type `Object`.

#### Example

Current `isEqualTo` implementation in `org.assertj.core.api.AbstractAssert#isEqualTo`
```java
  @Override
  public SELF isEqualTo(Object expected) {
    objects.assertEqual(info, actual, expected);
    return myself;
  }
```

Why it is not implemented in the following way?
```java
  @Override
  public SELF isEqualTo(ACTUAL expected) {
    objects.assertEqual(info, actual, expected);
    return myself;
  }
```

Then following check would not even compile instead of failing in runtime:
```java
    assertThat(1).isEqualTo("1");
```

Not sure if this change will break something, but if you think it will then we can add new assertion, something like `isEqual`.

**Comment by scordio** [comment]
> Why it is not implemented in the following way?

I think this is on purpose, following `Object.equals()`. There might be cases where you don't know the real type at compile time but still the runtime comparison would succeed using `Object`.

**Comment by Waltorw** [comment]
I think that `Object#equals` is implemented in that way because there were no generics back in the day, most of equals implementations (Intellij/Lombok generated ones at least) do check `instanceof` first and then cast to target type.
If we _really need_ to pass `Object` to the method we could just cast it directly on call site:
```java
Object one = 1;
assertThat(1).isEqualTo((Integer) one);
```

**Comment by joel-costigliola** [comment]
@Waltorw This was done at the time of Fest Assert, AssertJ ancestor, the main reason was to allow assertions like :
```
Object one = 1;
// would not work with generics 
assertThat(one).isEqualTo(1);
```
I personally encountered a few cases where it was handy like when you have `java.util.Date` and `java.sql.Date`.

Adding generics to `isEqualTo` is a breaking change and at the moment I don't see enough value for doing so.

I'm not convinced either to introduce a generic `isEqual()` version because the name does not clearly express the difference with `isEqualTo`.

**Comment by joel-costigliola** [comment]
Closing it but happy to hear further arguments

**Comment by feliksik** [comment]
The lack of a typesafe function is quite annoying. 

I do see there may be some exceptional cases where you may want to use the current type-unsafe one, and I also understand you don't want to introduce a breaking change. 

A typesafe function would allow for better refactoring, e.g. where you refactor a stringly-typed codebase to a more strongly typed codebase with value objects. 

However, I must admit that in that codebase, because of the prevalence of the current isEqualTo usage, probably that method would be used. Then still, however, I could replace all those usages with a possiblen generic-typesafe `<T> isEqual(T t)`

**Comment by scordio** [comment]
As mentioned in https://github.com/assertj/assertj/issues/1910#issuecomment-643572119, `isEqualTo` aims to keep the semantic of [`equals`](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-).

Having a strongly-typed parameter would close the door for cases where you don't know the real type at test compile-time.

**Comment by boris-faniuk-n26** [comment]
What about `isEqualToTypeSafe`? Then it's clear what this means.
Honestly, agree with @feliksik and @RamazanYapparov that in most of the cases type safe version is required.
How many use-cases have you ever met where you had to compare `java.sql.Date` and `java.util.Date` or you don't know the type at all?

BTW, in case someone missed this feature and has a privilege of using Kotlin, here's what I've done:

```kotlin
object AssertUtils {
    fun <SELF : Assert<SELF, ACTUAL>, ACTUAL> Assert<SELF, ACTUAL>.isEqualToTypeSafe(expected: ACTUAL): SELF =
        isEqualTo(expected)
}
```
