### ISSUE TITLE
New comparison strategy using bean-style getters

### ISSUE THREAD

**Issue by sithmein** [assertj/assertj#2108]
#### Summary
I like the recursive comparison strategy for `isEqualTo`. In addition I propose an new comparison strategy that works on public `getXXX()` methods. This makes it easy to compare beans with each other and at the same time also checking the getter implementations. This is especially useful when getters return `Optional`s, because I often found issue where `Optional.of()` was used when instead `Optional.ofNullable()` should have been used. Instead of writing a test for every single getter this could then be done with a single call.

#### Example

```java
public class Bean {
   private String s = null;
   
   public Optional<String> getS() { return Optional.of(s); } // coding error here
}

...
// This finds the error
assertThat(new Bean()).usingRecursiveBeanComparison().isEqualTo(new Bean());
```

**Comment by nach-o-man** [comment]
This seems pretty interesting. @joel-costigliola I give it a try if it seems like a good addition to existing features.

**Comment by joel-costigliola** [comment]
My preferred approach would be to add a `comparingOnlyGetters` (or a similar name) but before tackling this issue, I think we need to refactor the recursive comparison to use an introspection strategy, for this issue it would be use a implementation like `GetterIntrospectionStrategy`. 

This is actually related to https://github.com/assertj/assertj-core/issues/2149 where we would use a `FieldsOnlyIntrospectionStrategy`.

@nach-o-man maybe you can give a try to the refactoring, I have created https://github.com/assertj/assertj-core/issues/2189 but things might evolve as I don't have a fully clear picture in mind, at this stage it would be more a POC than anything.

**Comment by nach-o-man** [comment]
@joel-costigliola I am not that familiar with internals but I can give it a shot. Assign #2189 to me, please.

**Comment by BeshEater** [comment]
It will be really great for the codebase that is heavily reliant on DTO classes. Very often we have DTO with a simple String field, for example, email, that will be mapped from another object via the method getEmail(), and this other object doesn't have the email field at all. 
```java

// Heavy business object without fields but with standard getters
public class User {

    public String getEmail() {
        // Some complicated logic for email retrieval
        return "a@example.com";
    }
}

// Lightweight object for REST endpoint
public class UserDTO {
    private String email;

    public UserDTO(User user) {
        this.email = user.getEmail();
    }
}


var user = new User();
var userDto = new UserDTO(user);

assertThat(userDto).usingRecursiveComparison().isEqualTo(user);
```

**Comment by joel-costigliola** [comment]
@BeshEater and @sithmein, we have finally got the time to address  #2189 which is why I'm closing this issue.

@BeshEater I actually wrote a [test](https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L349) using an [introspection strategy](https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L229) that addresses this issue.

@sithmein, I also wrote a [test](https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L325) for your use case

I'm planning to expose the `ComparingProperties` introspection strategy implementation in AssertJ so that it's available out of the box for users like yourself (we'll likely do the same with `ComparingFields`).

Feel free to comment on the issue if you feel it's not fully addressed and we'll be happy to reopen it.
