### ISSUE TITLE
Can recursive comparison compare fields with the same name but different case style (snake_case vs cameCase)?

### ISSUE THREAD

**Issue by mikybars** [assertj/assertj#2554]
#### Summary

In our project we have some autogenerated classes that use snake case for field names (and we can't do anything about it). The problem we're encountering is that those names do not match our field names in the domain as they are camelCase. Is there any workaround for this?

**Comment by joel-costigliola** [comment]
No it's not possible at the moment but we are looking into making the introspection strategy being an interface that one can change and thus it could possible with a custom introspection strategy.

Making the introspection strategy is significant work so it might take a bit of time before being there.

**Comment by joel-costigliola** [comment]
@almibarss, we have finally got the time to address  #2189 which is why I'm closing this issue.

I actually wrote a test using an introspection strategy that matches camel and snake case fields, see:
* https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L123
* https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L178

Note that to work properly field names must normalized (I chose camel case in the test) because the recursive comparison checks whether actual field names are contained in expected field names.
A consequence of that is to get a field value by name, it checks first the camelCase name and then the snake case one if the camel case was not found. For example if actual field name is `lastName` and expected is `last_name`, `getChildrenNodeNamesOf` will return the normalized `lastName` for both, the normalized name is used to get the field value, that works fine for actual since this is exactly the field name, for expected, `lastName` won't be found but `last_name` will.
A bit tricky but works fine, @almibarss feel to give it a try, I'm happy to reopen the issue and improve the introspection strategy if it proved not to be flexible enough,

**Comment by almibarss** [comment]
It works like a charm! Good job! Any chance this camel vs snake case strategy gets to be an AssertJ built-in? It's a fairly common scenario IMO.

**Comment by joel-costigliola** [comment]
We can move `ComparingSnakeOrCamelCaseFields` to the main code so that it's available.
It would be good to have more tests for it though, would feel like contributing this one @almibarss?

**Comment by joel-costigliola** [comment]
cool, I'll reopen the issue then ;-)

**Comment by joel-costigliola** [comment]
@almibarss  have a look at how we tested `ComparingFields` in https://github.com/assertj/assertj/tree/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison

**Comment by joel-costigliola** [comment]
@mikybars have you got time/energy to work on this one ? it's ok if you don't, just let us know if that's the case

**Comment by mikybars** [comment]
Sure, you can count on me. Although I'm not entirely sure what's expected from me this time 😅

**Comment by joel-costigliola** [comment]
My bad, the `ComparingSnakeOrCamelCaseFields` is already available, I can close this one then. Thanks anyway for the quick reply.
