### ISSUE TITLE
Terminal operations should not return SELF

### ISSUE THREAD

**Issue by kannangce** [assertj/assertj#2830]
#### Feature summary

Terminal operations such as `org.assertj.core.api.AbstractAssert#isEqualTo` , `org.assertj.core.api.AbstractAssert#isNotEqualTo` , etc,  should not return `SELF`. The reason being, when you're writing the code, it let's you compose operations such as `withComparatorForFields`, `withFailMessage`, etc. But it is not actually used as the operation for the assertions already happened.

#### Example

The summary should be straight forward.

**Comment by scordio** [comment]
I think only in a few cases we can safely say that the assertion is terminal, like with `isNull` because you cannot do much with a null value.

After an `isEqualTo` call, you might still want to chain additional assertions to inspect getters, check private values via `extracting`, or chain more complex checks via `satisfies`.

**Comment by scordio** [comment]
Following the above rationale, I am rejecting this issue.
