### ISSUE TITLE
Recursive comparison unexpected for Exceptions

### ISSUE THREAD

**Issue by MeneDev** [assertj/assertj#2926]
**Describe the bug**

* assertj core version: 3.24.2
* java version: 17
* test framework version: junit-jupiter-5.9.2
* os (if relevant): 

**Test case reproducing the bug**

```java
@Test
void canCompareExceptionUsingRecursiveComparison() {
    assertThat(new Exception("some error")).usingRecursiveComparison().isEqualTo(new Exception("some error"));
}
```

Note that this works with 3.22.0

**Comment by joel-costigliola** [comment]
Thanks for reporting this @MeneDev.

**Comment by joel-costigliola** [comment]
The reason it fails is because the recursive comparison compares java types using their equals method, at some point a recursive comparison needs to compare values,  we have decided it would be java types (with special treatment for containers like collection or map).
thus indeed this raises the same error as: 
```java
assertThat(new Exception("some error")).isEqualTo(new Exception("some error"));
```
So what you could do is register a bipredicate to tell the recursive comparison how to compare `Exception`, for exampleyhis succeeds:
```java
assertThat(new Exception("some error")).usingRecursiveComparison()
                                       .withEqualsForType((e1, e2) -> e1.getClass().equals(e2.getClass())  && e1.getMessage().equals(e2.getMessage()), 
                                                          Exception.class)
                                       .isEqualTo(new Exception("some error"));
```

**Comment by joel-costigliola** [comment]
I wonder if we should add an option to force the recursive comparison on some given java types, not sure it that would work for  exception since it would mean to compare stack traces ...

**Comment by MeneDev** [comment]
I see, thanks for the explanation and the quick triage!

So just to clarify, the new behavior is intended, and we will need to add an equals override (using `withEqualsForType` or, in the future maybe with `compareExceptionByMessageAndType`) for versions after 3.22.0?

(I also wasn't aware `Exception`/`Throwable` has no equals implementation 😅)

For our test cases comparing stacktraces would not work, and I don't see how that would make sense as you would need to create a stacktrace from a different place (the test) than the actual position. Even if that's possible, it would be very brittle.

For most Exceptions comparing the types, the `message` and probably also the `cause` seems reasonable, but I guess for custom Exceptions all additional fields would be expected. So maybe adding a special treatment for `Throwable`, which excludes the stacktrace makes sense in the same way the special treatment for collection made sense?

**Comment by joel-costigliola** [comment]
I'm not sure there is a nice way to compare exceptions out of the box, for example what to do with stack trace and causes chain (it would have been in the JDK otherwise I think) so the team is leaning towards letting users implement their own (as I shown in my example).

I'll leave the issue open for discussion to hear arguments in favor of recursive comparison of exception or shipping an exception comparator.

**Comment by joel-costigliola** [comment]
Closing this issue now, feel free to comment and we'll reopen it.
