### ISSUE TITLE
make `asList()` type safe

### ISSUE THREAD

**Issue by Illutax** [assertj/assertj#3105]
#### Feature summary

The method `asList()` should return a correctly typed list.

#### Example

Assume a type `Bar` with the filed `strings: List<String>`. And a type `Foo` with the field `bar: List<Bar>` (both with default getter and all-args-constructor).

```java
class Foo {
  private final List<Bar> bars;
}

class Bar {
  private final List<String> strings;
}
```

The following block is type-safe
```java
import static java.util.Arrays.asList;

Bar bar = new Bar(asList("a","b"));
assertThat(bar)
  .extracting(Bar::getStrings)
  .asList()
  .containsExactly("a", "b");
```

When working with *nested* structures and using `Assert.asList()` the returned list will be of type Object.

```java
Foo myComplexFoo = new Foo(asList(new Bar(asList("a", "b")), new Bar(asList("a", "b"))));
assertThat(myComplexFoo)
  .extracting(Foo::getBars)
  .asList()
  .extracting(o -> ((Bar)o).getStrings())
  .containsExactly(asList("a", "b"), asList("a", "b"));
```

We had to cast the Object back to a Bar for working further with it.

The proposal creates an overload to the asList() which gets a type such that we can further assert the structure like:

```java
Foo myComplexFoo = new Foo(asList(new Bar(asList("a", "b")), new Bar(asList("a", "b"))));
assertThat(myComplexFoo)
  .extracting(Foo::getBars)
  .asTypedList(Bar.class)
  .extracting(Bar::getStrings)
  .containsExactly(asList("a", "b"), asList("a", "b"));
```

**Comment by Illutax** [comment]
I tried to wrestle with Javas' generic type system but it was fruitless.

I came up with a generic method where the type is bound by an additionally passed type argument.

```java
<T> AbstractListAssert<?, List<? extends T>, T, ObjectAssert<T>> asTypedList(Class<T> type);
```

Maybe it would be the better way to overload the `extracting` method instead?

**Comment by Illutax** [comment]
Ok, this works. But it is quite a mouthful and I'm sure that I will have to return to this issue for future reference.

I see that you implemented it in 2019, so I can imagine that you can remember it rather quickly.

Foo::getBars already returns Bar.class implicitly, why can't we utilize it instead?

**Comment by Illutax** [comment]
Would the assertj community benefit from the aforementioned `asTypedList(Class<T> type)`?

**Comment by scordio** [comment]
> I see that you implemented it in 2019, so I can imagine that you can remember it rather quickly.

Thank you for trusting my memory much more than I do 😄 

> Theoretically, we should be able to inline the InstanceOfAssertFactories.list(Bar.class) call inside the extract method. Or am I missing something?

If I recall correctly, that's not possible because the compiler must know that you want a `ListAssert` to be returned but there isn't enough information to infer that, as the return type of the getter provided as an input does not carry any `ListAssert` reference. That's why an additional parameter like `InstanceOfAssertFactories.list` is needed, to explicitly express such the desired mapping.

If you check how `InstanceOfAssertFactories.list` is defined, the mapping between the `List` type and the corresponding `ListAssert` becomes more visible, and you can spot `Assertions.assertThat(List)` as the factory method for the `ListAssert`:

https://github.com/assertj/assertj/blob/5bcd0c8484f4927156158671fcf6278c4bee8486/assertj-core/src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java#L898-L900

Of course, in case you have a better idea, happy to discuss it! 🙂 

> Would the assertj community benefit from the aforementioned `asTypedList(Class<T> type)`?

This would go in the direction of #1020, further discussed in https://github.com/assertj/assertj/issues/1020#issuecomment-311290894 but eventually not implemented.

In general, we might even argue why we still keep `asList` alive, while there is no `asSet` or `asMap`. `asList` is also available in all subtypes of `AbstractAssert` although it's obvious that in most of them `actual` is never a list.

To give the full picture, many `asXXX` methods were added in the past (3d9e0f56) but eventually reverted (4d1342dd) as the `Assert` API bloated. The advantage of `asInstanceOf` is that the API is not bloated and it's fully extendable with custom types, at the expense of a bit of verbosity as you also pointed out.

Lastly, 3.25.0 will introduce additional `as` methods (#2580) to `String` assertions which are not pure cast operations like `asList` but more parsers of the current value.

Pushed to the extreme, I believe the existing `asList` could even be deprecated in favor of `asInstanceOf`.

**Comment by Illutax** [comment]
When discussing assertion libraries my favourite point for AssertJ is the tool assisting, when writing assertions. "You can just write `asserThat(something)` and after adding a period you get a reasonable list of things you can add. Hamcrest has also a lot of flexibility but there you have to use a cookbook with all available matchers to draw from when writing assertions.

This is why I would prefer a typed `asList` or an `asInstanceOf` over a second argument to the extract method. On the other hand, the tool assistance with suggestions of the methods from InstaceOfAssertFactories is quite good and with a static import it's not overly cluttered.

I am taking back my proposal, thank you for the discussion!

I think we are blocked by the javac until Oracle comes to a breakthrough with [JEP 101](https://openjdk.org/jeps/101).

**Comment by scordio** [comment]
I totally agree with you, @Illutax, and should have given more focus to the language limitation rather than the AssertJ design choice, but you got that point anyway 🙂 

Let's see what options JEP 101 will provide.
