### ISSUE TITLE
isEqualToNormalizingWhitespace doesn't normalise non breaking space characters

### ISSUE THREAD

**Issue by ArneKlein** [assertj/assertj#3113]
**Describe the bug**
isEqualToNormalizingWhitespace doesn't normalise non breaking space characters

* assertj core 3.21:
* java version: 17
* Kotlin 1.9.0
* test framework version: JUnit 5.9.1
* os (if relevant): 

**Compare 2 strings with one having a [NBSP](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-typography/nbsp.html) character instead of a normal space**

```Kotlin
val result = "10,00 € to 100NBSP000,00 € per year"
val expected = "10,00 € to 100 000,00 € per year"
assertThat(result).isEqualToNormalizingWhitespace(expected)
```

**Comment by joel-costigliola** [comment]
That's a bit weird since the [implementation](https://github.com/assertj/assertj/blob/776b46c514c4336c58a643fb08bf61a1ac6cb9b3/assertj-core/src/main/java/org/assertj/core/internal/Strings.java#L455) detects the whitespace characters according to the JDK `Character` method [isWhitespace](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Character.html#isWhitespace(char)) that includes non-breaking space characters.

Could you attach a test case in a PR, reason is a test in a github comment may or may not honor the non-breaking space characters when we copy it to our codebase.

Thanks!

**Comment by maximedezette** [comment]
@joel-costigliola the documentation of the `isWhitespace` method seems to indicate that the non-breaking spaces are  not consider as regular whitespaces.

I've added this test case locally that seems to confirm that:

`should_pass_if_both_Strings_are_equal_after_whitespace_is_normalized`

![image](https://github.com/assertj/assertj/assets/27780296/fd328e59-6e16-4b9b-b625-938321c71193)

I've also noticed that the `isNotBlank `assertion is `false` if a string is filled with non-breaking spaces because it uses the `isWhitespace `method as well (I think that's the expected behavior because some unit tests have been specifically added).

I think that the non-breaking spaces `('\u00A0', '\u2007', '\u202F')` should be replaced in the `normalizeWhitespace` method. 

Is it ok if I work on this issue ? I think this might be a good first issue 🙂

**Comment by maximedezette** [comment]
I had some spare time so I gave it a try: https://github.com/assertj/assertj/pull/3120 😅

**Comment by scordio** [comment]
> @joel-costigliola the documentation of the `isWhitespace` method seems to indicate that the non-breaking spaces are not consider as regular whitespaces.

Specifically:

> Determines if the specified character is white space according to Java. A character is a Java whitespace character if and only if it satisfies one of the following criteria:
> * It is a Unicode space character (`SPACE_SEPARATOR`, `LINE_SEPARATOR`, or `PARAGRAPH_SEPARATOR`) but is not also a non-breaking space (`'\u00A0'`, `'\u2007'`, `'\u202F'`). 
> * ...

Should we actually move away from what the JDK does, or should we only improve the Javadoc to state more clearly that these assertions follow the `Character::isWhitespace` behavior?

In the case of the latter, it would be nice to identify a workaround, if there is any.

**Comment by joel-costigliola** [comment]
I'm happy we extend the definition of whitespace **and** we update the javadoc to clearly show what we mean by it.
