### ISSUE TITLE
Recursion comparison using properties ignores default interface methods.

### ISSUE THREAD

**Issue by rpiterman** [assertj/assertj#3125]
If an Object has methods defined as default methods in an interface, these are not detected by the ComparingProperties() introspection strategy:

for example:

```
public interface Bar {
  default String getName() {
     return "bar";
  }
}

public class Foo implements Bar {
}
```

expected:

ComparingProperties should also detect properties defined in as default methods in interfaces implemented by the target object.

**Comment by amodolo** [comment]
`ComparingProperties` collect the properties scanning the declared method for each class in the hierarchy.
In particular, the method `gettersIncludingInheritedOf(Class)` collect all the methods declared in the passed class object using the `Class.getDeclaredMethods()` API and iterate the process considering the superclass until the fundamental package `java.lang.`

In this way, this implementation takes into account only the properties inherited by the extension, and that's the reason why the default methods, declared in the interfaces, are ignored.

I think that collecting the properties using the `getMethods` API should be  a better approach because:
-  it returns all public methods considering both superclasses and interfaces
-  there's no need to filter public methods
-  there's no need to iterate through the class hierarchy 

I create a PR to let the AssertJ maintainers evaluate the fix proposal.

**Comment by joel-costigliola** [comment]
Fixed by https://github.com/assertj/assertj/pull/3135
