### ISSUE TITLE
Maven default goal is not set at the right place

### ISSUE THREAD

**Issue by Bananeweizen** [assertj/assertj#3181]
**Describe the bug**
The assertj parent module contains a maven default goal. That's the wrong place to define a default goal, because the default goal is not something that gets inherited by the children of that parent. Instead it must be set in the reactor (the root directory pom.xml).

**Comment by scordio** [comment]
Actually, I don't see why we should have a default goal.

Even if we would keep it, `clean install` is definitely [not a good default](https://andresalmiray.com/maven-verify-or-clean-install/).

**Comment by Bananeweizen** [comment]
I completely agree on "clean install" not being a good default goal. I just took what was there. However, if assertj is one of the good projects that builds without issues when using "verify" only (without clean and without install), then the best place to document that is by actually having that as default goal. Otherwise contributors not familiar with the project will always assume the worst and still run "clean install", wasting time and resources. At least my personal thinking is that any project with a declared default goal will work that way, and any build error can be reported as failure immediately. In projects without default goal I assume that I might have to look for some magic with 3 different goals, an additional profile and some -D settings. :)

Would you agree on using "verify" only as default goal then?

**Comment by scordio** [comment]
We expect contributors to have basic familiarity with Java and Maven. Even if a user would run a `clean install` on AssertJ, no one will get hurt 😄 

Our CI configuration can also serve as a reference on how the project is supposed to be built:

https://github.com/assertj/assertj/blob/1a740618887eea3b4f09fad52bf811e9717bc884/.github/workflows/main.yml#L25-L26

and the `javadoc` goal is definitely optional for a local build (I actually have in mind to extract it to a separate workflow).

Especially because we don't require a magic combination of goals or special variables to be used, I'd still favor not having a default goal at all in the POM.
