### ISSUE TITLE
Add an alias of `matches` with `tests`

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#3215]
#### Feature summary

I just found that we already have [`AbstractAssert#matches(Predicate)`](https://javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractAssert.html#matches(java.util.function.Predicate)).

And I'm pretty sure that assertion added before the [`AbstractCharSequenceAssert#matches(...)`](https://javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractCharSequenceAssert.html#matches(java.lang.CharSequence)) added.

We can add an alias for the `matches(Predicate)` method, whenever possible.

#### Example

```java
//assertThat(new Object()).matches(Objects::nonNull); // alias of matches(Predicate)
assertThat(new Object()).tests(Objects::nonNull); // alias of matches(Predicate)
assertThat("").matches(""); // REGEXP
<add example here>
```

**Comment by scordio** [comment]
I'm not sure `tests` would be a proper method name because what is under test is not the `Predicate` but the argument for it. An alternative could be `isTestedBy` but I don't feel it is natural enough.

Looking at the `Predicate` Javadoc, [`test`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/function/Predicate.html#test(T)) mentions:

> Evaluates this predicate on the given argument.
>
> **Parameters:**
>     `t` - the input argument
> **Returns:**
>     `true` if the input argument matches the predicate, otherwise `false` 

so the `matches` method name doesn't seem so bad after all.

I understand we have a bit of a naming clash in `AbstractCharSequenceAssert` but both use cases seem to have a good name if you look at the underlying JDK feature 🤷
